import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import NextImage from "next/image";
import ScrollProgress from "../components/ScrollProgress";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  weight: ["700","800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wolves",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="force-light">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="site-header sticky top-0 z-50">
          <ScrollProgress />
          <div className="max-w-[1200px] mx-auto px-2 sm:px-4 h-14 flex items-center justify-between">
            <a href="/" className="brand-link flex items-center gap-3">
              <span className="brand-logo" aria-hidden="true">
                {/* Decorative rounded mark */}
                <svg width="36" height="36" viewBox="0 0 36 36" fill="none" xmlns="http://www.w3.org/2000/svg" className="rounded-mark">
                  <rect width="36" height="36" rx="8" fill="#2563eb" />
                  <path d="M10 23L14.5 12L18 18L22.5 10L26 23" stroke="white" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </span>

              <span className="brand-name bg-gradient-to-r from-[#2563eb] to-[#7cc0ff] bg-clip-text text-transparent font-extrabold">Wolves</span>
            </a>
            <nav className="header-nav hidden sm:flex items-center gap-4">
              <a href="#results" className="nav-link">Results</a>
              <a href="#pricing" className="nav-link">Pricing</a>
              <a href="#testimonials" className="nav-link">Testimonials</a>
              <a href="#faqs" className="nav-link">FAQs</a>
            </nav>
            <div className="flex items-center gap-3">
              <a href="https://t.me/wolves29" className="header-cta">Contact</a>
              <a href="#hero" className="header-ghost-cta">Get Started</a>
            </div>
          </div>
        </header>
        <main className="site-main">{children}</main>
      </body>
    </html>
  );
}
